---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

I am largely interested in the study of memory from a cognitive perspective, as there is still much to explore about the features and boundaries of working memory in all forms. I have previously focused on much more rudimentary motor skill learning tasks, which have introduced me to creating my own web experiment with JavaScript, HTML, and CSS. With the paper I chose being focused on visual working memory (VWM), I feel sufficiently challenged by coding a completely different kind of paradigm in a format I'm familiar with. The first experiment in the paper yielded a very strong confirmation of repulsion as a VWM phenomenon, as the results showed participants were "better at rejecting a foil color that was distorted toward the non-target memory item than rejecting a foil color that was distorted away from the non-target memory item" (Chunharas, 2022).

For this replication, I will need to reproduce the 2-AFC color wheel VWM task from Experiment 1 in an online format, able to be conducted on SONA. I will have to re-code it in Javascript, HTML, and CSS, as opposed to original experiment which used MATLAB and Psychophysics toolbox. Thankfully, the first experiment was also conducted online, so the format will be perceptually indistinguishable for the participant. I can foresee many hurdles when reproducing this task in a different language, however by utilizing the "Stimuli & Procedure" section under Experiment 1, I will be able to make sure the task is identical in presentation. The post-hoc data analysis I will be conducting will be a paired t-tests on accuracy. The original results showed toward vs. away gave t(44)=3.98, p<.001, toward vs. chance gave t(44)=3.73, p=.006, and away vs. chance gave t(44)=-1.76, p=.08.

The first task I coded was much simpler than this, and was concerned mainly with precision of recording input, not precision with displaying stimuli, so working with changing stimuli on a screen will be new. In my original experiment, I also received a substantial amount of help with the code structure, debugging, and most of the work in HTML and CSS.

Here is a link to the code and data from the paper: https://osf.io/qp6xk/?view_only=0559769c587c4c8294288451e8af239e

Link to Repository: https://github.com/jamesrashby21/brady2022

Link to Replication Paper: https://dx.doi.org/10.1037/xlm0001014

-------------------------------------------------------------------------------

[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information. You will likely contact the authors of the original study, so this should be professional and forward facing. It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
